Add files.
jbej/Webpack_ToDoList pull request #1
Opened 2018-04-20 20:32 UTC by jbej

2018-04-22 07:19 UTC, matwjablonski requested changes

2018-04-22 07:19 UTC, matwjablonski commented on src/components/TodoList.js
> +
why to many empty lines?

2018-04-22 07:19 UTC, matwjablonski commented on src/index.js
> +		const NaxtApp = require('./containers/App').default;
Naxt? :)

2018-04-23 17:20 UTC, jbej commented on src/index.js
> +		const NaxtApp = require('./containers/App').default;
NextApp - because it's in Kodilla's materials.

2018-04-23 18:40 UTC, matwjablonski requested changes

2018-04-23 18:40 UTC, matwjablonski commented on src/components/TodoList.js
>  		remove={props.remove} iform={props.iform}/>)
add semicolon

2018-04-26 11:05 UTC, matwjablonski approved these changes

2018-05-27 16:51 UTC, merged